### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by pillai-karthik** [sukhitashvili/pencil_sketches#3]
Amazing repository!

Can you please add the training code so that we can improve the model and to see how it was trained?

Thank you!

**Comment by sukhitashvili** [comment]
Hi,

Glad you like the repo!

I took model from this [repo](https://github.com/bobbens/sketch_simplification) and I rewrote its definition into newer version of PyTorch and added openCV pre-processors. You should find data and training scripts there.

Also, I suggest you to try stable diffusion model with [textual inversion](https://textual-inversion.github.io/) trick. Back then when I created this repo there was no stable diffusion method/technology.
